CHANGELOG.md, build.gradle, config/checkstyle/checkstyle.xml, src/main/java/au/com/sealink/quicktravel/client/models/barcodes/BaseTicket.java, src/main/java/au/com/sealink/quicktravel/client/models/barcodes/ITicket.java, src/main/java/au/com/sealink/quicktravel/client/models/barcodes/IssuedTicket.java, src/main/java/au/com/sealink/quicktravel/client/models/barcodes/core/ConsumerTypeCount.java, src/main/java/au/com/sealink/quicktravel/client/services/TicketScanner.java, src/test/java/au/com/sealink/quicktravel/client/models/barcodes/ConsumerSplitTicketTest.java, src/test/java/au/com/sealink/quicktravel/client/models/barcodes/IssuedTicketTest.java, src/test/java/au/com/sealink/quicktravel/client/models/barcodes/ReservationTicketTest.java, src/test/java/au/com/sealink/quicktravel/client/services/TicketScannerTest.java
Adds linting based upon Google base file format (excluding JavaDoc requirement and indentation is set to IntelliJ defaults)
No code changes
=> Tt 4022 add linting support

CHANGELOG.md, README.md, build.gradle, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java, src/main/java/au/com/sealink/quicktravel/client/models/BoardRequest.java, src/main/java/au/com/sealink/quicktravel/client/models/BoardResult.java, src/main/java/au/com/sealink/quicktravel/client/models/ErrorBody.java, src/main/java/au/com/sealink/quicktravel/client/models/PaymentType.java, src/main/java/au/com/sealink/quicktravel/client/models/ProductType.java, src/main/java/au/com/sealink/quicktravel/client/models/Resource.java, src/main/java/au/com/sealink/quicktravel/client/models/ResourceCategory.java, src/main/java/au/com/sealink/quicktravel/client/models/ServerScan.java, src/main/java/au/com/sealink/quicktravel/client/models/ServerScanErrorCode.java, src/main/java/au/com/sealink/quicktravel/client/models/User.java, src/main/java/au/com/sealink/quicktravel/client/models/timetable/Departure.java, src/main/java/au/com/sealink/quicktravel/client/models/timetable/Route.java, src/main/java/au/com/sealink/quicktravel/client/models/timetable/TimeTable.java, src/test/java/au/com/sealink/quicktravel/client/models/barcodes/ReservationTicketTest.java, src/test/resources/fixtures/reservation_barcode_without_todo.json
Adds initial API support for Mobile Companion application
=> Tt 4168 add api support

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java
Allow filtering of resource categories by ids and product_type_ids
=> Tt 4200 add product type ids

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java, src/main/java/au/com/sealink/quicktravel/client/models/EncryptedData.java, src/test/java/au/com/sealink/quicktravel/client/models/EncryptedDataTest.java, src/test/resources/fixtures/encrypted_data.json
**WHY**
New endpoint to convert ticket reference number into a barcode
=> Tt 4238 barcode endpoint

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java, src/main/java/au/com/sealink/quicktravel/client/models/Route.java, src/main/java/au/com/sealink/quicktravel/client/models/RouteStop.java, src/test/java/au/com/sealink/quicktravel/client/models/RouteTest.java, src/test/resources/fixtures/route.json
Add support for the api/routes endpoint in QuickTravel
=> TT 4368 route support

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java, src/main/java/au/com/sealink/quicktravel/client/models/checkout/Checkout.java, src/main/java/au/com/sealink/quicktravel/client/models/checkout/CheckoutResponse.java, src/main/java/au/com/sealink/quicktravel/client/models/checkout/Payment.java, src/test/java/au/com/sealink/quicktravel/client/models/checkout/CheckoutResponseTest.java, src/test/java/au/com/sealink/quicktravel/client/models/checkout/CheckoutTest.java, src/test/resources/fixtures/checkout_create.json, src/test/resources/fixtures/checkout_response.json
WHY
Allow payment creation against bookings
=> Tt 4435 payment creation

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java
###
Why expose some of the endpoints that are required to handle booking information in quicktravel
=> TT 4432 booking endpoints

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java, src/main/java/au/com/sealink/quicktravel/client/models/Country.java, src/test/java/au/com/sealink/quicktravel/client/models/CountryTest.java, src/test/resources/fixtures/country.json
WHY
API endpoint to retrieve countries
=> Tt 4451 countries api

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java, src/main/java/au/com/sealink/quicktravel/client/models/Till.java, src/test/java/au/com/sealink/quicktravel/client/models/TillTest.java, src/test/resources/fixtures/till.json
WHY
Api endpoint to retrieve tills
=> Tt 4452 tills api

CHANGELOG.md, build.gradle, src/main/java/au/com/sealink/quicktravel/client/retrofit/HostSelectionInterceptor.java, src/test/java/au/com/sealink/quicktravel/client/retrofit/HostSelectionInterceptorTest.java
Why
Different tenants require different hostnames, this makes it trivial to switch
=> TT 4450 host intercept

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java, src/main/java/au/com/sealink/quicktravel/client/models/reservationFor/core/Product.java, src/test/java/au/com/sealink/quicktravel/client/models/reservationFor/core/ProductTest.java, src/test/resources/fixtures/product.json
WHY
Allows creation of bookings
=> Tt 4449 create booking

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/services/analytics/AnalyticsEvent.java, src/main/java/au/com/sealink/quicktravel/client/services/analytics/AnalyticsService.java, src/test/java/au/com/sealink/quicktravel/client/services/analytics/AnalyticsEventTest.java
Defines an interface that can be implemented in applications to provide analytics support.
=> Tt 4446 analytics service

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/services/analytics/AnalyticsEvent.java, src/main/java/au/com/sealink/quicktravel/client/services/analytics/AnalyticsService.java
WHY
Service definition was incorrect.
=> Tt 4459 fix analytics service definition

src/main/java/au/com/sealink/quicktravel/client/models/createParty/Contact.java, src/test/java/au/com/sealink/quicktravel/client/models/CreatePartyTest.java, src/test/resources/fixtures/create_person_request.json
Reopen PR as I missed contact name
=> Tt 4568 add client creation

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java, src/main/java/au/com/sealink/quicktravel/client/models/IssuedTicket.java, src/main/java/au/com/sealink/quicktravel/client/models/IssuedTicketValidationResponse.java, src/main/java/au/com/sealink/quicktravel/client/models/barcodes/core/TicketTemplate.java, src/test/java/au/com/sealink/quicktravel/client/models/IssuedTicketTest.java, src/test/java/au/com/sealink/quicktravel/client/models/IssuedTicketValidationResponseTest.java, src/test/resources/fixtures/issued_ticket_validation_response.json
**WHY**  
Adds support to the API to support validation of tickets, also adds the core IssuedTicket model
=> Tt 4700 add issuedtickets validate

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/models/barcodes/OnlineTicket.java, src/main/java/au/com/sealink/quicktravel/client/models/barcodes/core/Format.java, src/main/java/au/com/sealink/quicktravel/client/services/TicketScanner.java, src/test/java/au/com/sealink/quicktravel/client/models/barcodes/OnlineTicketTest.java, src/test/java/au/com/sealink/quicktravel/client/services/TicketScannerTest.java, src/test/resources/fixtures/online_ticket_barcode.json
**WHY**
Add support for new ticket format.
=> Tt 4699 new ticket format

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java, src/main/java/au/com/sealink/quicktravel/client/models/checkout/Status.java, src/test/java/au/com/sealink/quicktravel/client/models/checkout/StatusTest.java, src/test/resources/fixtures/checkout_status_complete.json, src/test/resources/fixtures/checkout_status_error.json, src/test/resources/fixtures/checkout_status_progress.json
WHY
Adds support for the checkout status endpoint
=> Tt 5280 additional checkout endpoints

CHANGELOG.md, gradle/wrapper/gradle-wrapper.properties, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java, src/main/java/au/com/sealink/quicktravel/client/models/Vessel.java, src/test/java/au/com/sealink/quicktravel/client/models/VehicleTypeTest.java, src/test/java/au/com/sealink/quicktravel/client/models/VesselTest.java, src/test/resources/fixtures/vessel.json
Adds support for the api/vessels endpoint which is required by the SSA
=> Tt 6453 add vessel endpoint

CHANGELOG.md, build.gradle, src/main/java/au/com/sealink/quicktravel/client/retrofit/UserAgentInterceptor.java, src/main/resources/version.properties, src/test/java/au/com/sealink/quicktravel/client/retrofit/UserAgentInterceptorTest.java, src/test/resources/version.properties
Adds a retrofit interceptor for the purpose of passing through user agent, and other client information
=> Tt 8144 add useragent interceptor

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/models/barcodes/core/Resource.java, src/main/java/au/com/sealink/quicktravel/client/models/timetable/Departure.java, src/test/java/au/com/sealink/quicktravel/client/models/barcodes/ReservationTicketTest.java, src/test/java/au/com/sealink/quicktravel/client/models/timetable/DepartureTest.java, src/test/resources/fixtures/departure.json, src/test/resources/fixtures/reservation_barcode_with_masterpoint.json
Adds the required API fields for the barcode scanner to handle masterpointed scheduled trips
=> Add recent API additions required for masterpointed scanning

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/models/Resource.java, src/test/java/au/com/sealink/quicktravel/client/models/ResourceTest.java, src/test/resources/fixtures/resource.json
Expose the masterpoint resource id property on the resource object
=> Tt 8250 add masterpoint resource

.github/workflows/gradle.yml, CHANGELOG.md
**WHY**
Trigger workflow by pushing Tag
=> PLAT-27 Trigger workflow by pushing Tag

CHANGELOG.md, src/main/java/au/com/sealink/quicktravel/client/QuickTravelApiClient.java
QuickTravel API was changed to accept visibility_mode and scope was deprecated
=> Plat 44 update api param
